/*
    > (SINAL DE MAIOR)
    < (SINAL DE MENOR)
    >= (SINAL DE MAIOR OU IGUAL)
    <= (SINAL DE MENOR OU IGUAL)
    == (SINAL DE IGUAL) OBS: NO JS ESSE SINAL CHECA APENAS O VALOR 
    === (SINAL DE IGUAL - ESTRITO) ELE CHECA TANTO O VALOR E O TIPO
    != (SINAL DE DIFERENTE)  OBS: NO JS ESSE SINAL CHECA APENAS O VALOR 
    !== (SINAL DE DIFERENTE - ESTRITO) ELE CHECA TANTO O VALOR E O TIPO
*/

let numero = '10';
let numero1 = 20;

const recebe = numero != numero1;
console.log(recebe);