/*
    (ARRAY) - É UMA LISTA OU UMA COLEÇÃO DE COISAS. POR EXEMPLO, EM UMA STRING É POSSIVEL COLOCAR UM TEXTO CERTO?
    PORÉM, IMAGINA QUE VOCÊ DESEJA COLOCA EM UMA STRING, UMA LISTA DE ALUNOS CONFORME ABAIXO:

    let alunos = 'João, Maria, jose, Francisco'

    CONFORME ACIMA, FOI CRIADO UMA VARIAVEL CHAMADO (ALUNOS) E NELA POSSUI UM TEXTO, COM OS NOMES. MAS SE CASO QUEIRA, SUBSTITUIR O NOME DO JOSE POR UM OUTRO NOME, É POSSIVEL? SIM É POSSIVEL, POREM PODE SE TORNAR COMPLEXO DEPENDENDO DO CODIGO. PORTANTO, PODEMOS FACILITAR UM POUCO ESSA SITUAÇÃO OU QUALQUER OUTRA QUE SEJA SEMELHANTE, TRABALHANDO COM (ARRAY)

*/

/*
    1° PARA CRIAR UMA LISTA DE NOMES OU QUALQUER OUTRA COISA, BASTA ABRIR E FECHAR OS COLCHETES [] CONFORME ABAIXO:
    OBS: DENTRO DOS COLCHETES, ALEM DE STRINGS, É POSSIVEL COLOCAR (NUMEROS, VALOR BOOLEANOS, NULL,FUNÇÕES) ETC POIS NO JS NÃO HÁ RESTRIÇÃO, E ISSO NÃO É UMA BOA PRÁTICA DE PROGRAMAÇÃO.
                                                                                                         1234567891011 
    2° CONFORME JÁ EXPLICADO NA PASTA (7 - Aprofundando em (STRINGS) ) AS STRINGS SÃO INDEXADAS. POR EX: ALEX SANTOS OU SEJA, EXISTE 11 INDICES. NO ARRAY NÃO É DIFERENTE, POIS OS ARRAYS TAMBÉM SÃO INDEXADAS. PORÉM, NÃO PELO VALOR IGUAL O EX DA STRING, MAS SIM PELO ELEMENTO VEJA ABAIXO
                      0       1       2       3
    const alunos = ['joão','Maria','Jose','Francisco'] 

    VEJA NA PRATICA: 
*/

//USO DA STRING PARA CAPTURAR O VALOR CHAMADO ALEX
const nome = 'Alex, Júlia, Anderson';
console.log(nome.slice(0,4));

//USO DO ARRAY PARA CAPTURAR O VALOR CHAMADO ALEX
const alunos = ['Alex', 'Júlia', 'Anderson'];
//VEJA QUE NÃO FOI PRECISO APLICAR O METODO SLICE PARA CAPTURAR OS VALORES. 
console.log(alunos[0]); //CAPTURANDO O ELEMENTO QUE ESTÁ NO INDICE [0] RESP: Alex

//TAMBÉM É POSSIVEL EXIBIR TODOS OS VALORES DOS INDICES DECLARADO NO ARRAY
console.log(alunos); //EXIBINDO TODOS OS INDICES QUE ESTÃO NO ARRAY RESP: [ 'Alex', 'Júlia', 'Anderson' ]


alunos[0] = 'Maria';
console.log(alunos);

alunos[3] = 'Jose';
console.log(alunos);